#!/usr/bin/env ruby

require "./lib/titlizer"

sites_parser = Titilizer::Parser.new(sites: ARGV, max_concurrent_requests: 64)
sites_parser.parse!
results = sites_parser.results

terminal_table = Titlizer::Seiralizers::PasrserResult::TerminalTableSerializer.new(results).serialize
puts terminal_table.render(:ascii, padding: [0, 1, 0, 1])
